apiVersion : apps/v1
kind: Deployment
metadata:
  name: workeracoesmsreactor 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workeracoesmsreactor
  template:
    metadata:
      labels:
        app: workeracoesmsreactor 
    spec:
      containers:
        - name: workeracoesmsreactor 
          image: groffeazuredevops.azurecr.io/workeracoesmsreactor
          env:
          - name: ConnectionStrings__RedisServer
            valueFrom:
              secretKeyRef:
                name: workeracoes-secret
                key: RedisConnection
          - name: ApacheKafka__Topic
            value: topic-acoes-testes
          - name: ApacheKafka__GroupId
            value: workeracoes
          - name: ApacheKafka__Broker
            valueFrom:
              secretKeyRef:
                name: workeracoes-secret
                key: KafkaBroker
          - name: ApacheKafka__Username
            valueFrom:
              secretKeyRef:
                name: workeracoes-secret
                key: KafkaUsername
          - name: ApacheKafka__Password
            valueFrom:
              secretKeyRef:
                name: workeracoes-secret
                key: KafkaPassword                                