apiVersion: v1
kind: Secret
metadata:
  name: workeracoes-secret
type: Opaque
data:
  RedisConnection: REDIS CONNECTION STRING BASE 64
  KafkaBroker: KAFKA CONNECTION STRING BASE 64
  KafkaUsername: KAFKA USERNAME STRING BASE 64
  KafkaPassword: KAFKA PASSWORD STRING BASE 64